In [1]:
import cv2
import numpy as np
link='../../vid/drone-flight.mp4'

def scale(frame, factor=.5):
    height, wid, _ = frame.shape
    scaled_wid, scaled_height = np.int(wid * factor), np.int(height * factor)
    frame = cv2.resize(frame, (scaled_wid, scaled_height))
    return frame


cap = cv2.VideoCapture(link)
while True:
     # Capture frame-by-frame
    ret, frame = cap.read()
    frame = scale(frame, factor=.25)
    orb = cv2.ORB_create()

    # find the keypoints with ORB
    kp = orb.detect(frame, None)

    # compute the descriptors with ORB
    kp, des = orb.compute(frame, kp)
    print(des)
    frame2 = cv2.drawKeypoints(frame, kp, None, color=(0,255,0), flags=0)
    cv2.imshow('frame2', frame2)
    k = cv2.waitKey(60) & 0xff
    if k == 27:
        break
cap.release()
cv2.destroyAllWindows()

[[164 225 237 ... 248 214 162]
 [110 206  74 ... 191  88  80]
 [125 165 173 ... 120 208  34]
 ...
 [236  96 249 ... 243  70  99]
 [ 85  76 111 ... 179   0  97]
 [108 162 184 ... 203 206  35]]
[[145 141  95 ... 170 112  56]
 [  5 150 253 ... 224 193 165]
 [142 107 145 ...  55  67 136]
 ...
 [ 85  76 111 ... 179   0  97]
 [ 47  94 123 ... 191  53 245]
 [108 162 184 ... 203 206   3]]
[[245 108  76 ... 241  74   8]
 [ 72 165  88 ... 200 195 130]
 [ 77 122 185 ... 246   7 117]
 ...
 [108  96 185 ... 243  70  99]
 [ 85  76 111 ... 243   0  97]
 [ 15  94 107 ... 191  53 241]]
[[ 49   3 107 ... 138 242 168]
 [184 192 246 ... 252 124 138]
 [ 65 177 249 ... 194 135 241]
 ...
 [ 74 109 234 ... 116 255 218]
 [ 69  64 223 ... 243   1 113]
 [236  96 185 ... 243  70  99]]
[[170 223 118 ...  28  45 223]
 [ 56 236  62 ...  12 142 138]
 [119 216  66 ...  12 237 223]
 ...
 [ 74 109 234 ... 116 247 218]
 [ 69  64 223 ... 243   1 113]
 [236  98 184 ... 243  70  99]]
[[144 133 181 ...  98 231 246]
 [252 163

In [18]:
des[0]

array([105, 169, 172, 103,  61, 157,  73,  31,  75, 249, 172,  76, 178,
         9,  86, 182, 137, 110, 120,  28, 139, 104, 251,  17, 207, 221,
       149, 124,  74,  14,  90, 120], dtype=uint8)