In [1]:
import cv2
import numpy as np

In [68]:
image = cv2.imread('../../../img/original/img7.jpg')
print(isinstance(image, np.ndarray))
# image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = cv2.resize(image, (0,0), fx=0.5, fy=0.5)
image_blur = cv2.GaussianBlur(image, (7, 7), 0)
hsv = cv2.cvtColor(image_blur, cv2.COLOR_RGB2HSV)
lower_range = np.array([150, 0, 255 - 60])
upper_range = np.array([179, 255, 255])   
mask = cv2.inRange(hsv, lower_range, upper_range)
result2 = cv2.bitwise_and(image, image, mask=mask)
cv2.imshow('image', image)
cv2.imshow('result2', result2)
cv2.waitKey(0)        
cv2.destroyAllWindows()

True


In [14]:
image = cv2.imread('../../../img/original/img7.jpg')
isinstance(image, np.ndarray)

True

In [31]:
# [105 154 152]
# rgb [152 154 105]
print(image[472, 230])

[152 154 105]


In [32]:
# [102 146 141]
# rgb [141 146 102]
print(image[440, 250])

[141 146 102]
